# A simple CRD to deploy a demo website from a git repo
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: demowebs.baeke.info
spec:
  scope: Namespaced
  group: baeke.info
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                nodeport:
                  type: integer
                backendName:
                  type: string
                backendImage: 
                  type: string
                backendContainerPort: 
                  type: integer
                backendNodePort: 
                  type: integer
                frontEndName: 
                  type: string
                frontEndImage: 
                  type: string
                frontEndContainerPort: 
                  type: integer
                frontEndNodePort: 
                  type: integer
  names:
    kind: DemoWeb
    plural: demowebs
    singular: demoweb
    shortNames:
      - dweb
  
          