apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim  
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: mysql-pv-volume

