apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: poonam3112/front-end-new:v1
        ports:
        - containerPort: 80
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: BACKEND_BASE_URL
          value: "http://$(MY_POD_IP):32000/"



---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
